-- ═══════════════════════════════════════════════════════════════════
-- Churrasco na Marmita — tabelas de PRODUTOS e CONFIGURAÇÃO
-- Execute este script no Supabase > SQL Editor (uma vez por projeto)
-- ═══════════════════════════════════════════════════════════════════

-- 1) Produtos (cardápio)
CREATE TABLE IF NOT EXISTS produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  preco numeric NOT NULL DEFAULT 0,
  descricao text,
  imagem text,
  categoria text DEFAULT 'meal',          -- meal (marmita) | drink (bebida) | dessert (sobremesa)
  ativo boolean DEFAULT true,
  ordem int DEFAULT 0,
  criado_em timestamptz DEFAULT now()
);

-- 2) Configuração da loja (nome, telefone, logo etc.)
CREATE TABLE IF NOT EXISTS config (
  id bigint PRIMARY KEY DEFAULT 1,
  nome_loja text,
  descricao_loja text,
  telefone text,
  endereco text,
  instagram text,
  logo text,
  banner text,
  atualizado_em timestamptz DEFAULT now()
);
INSERT INTO config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 3) RLS — mesmo padrão simples já usado nas tabelas status/pedidos:
--    anon pode ler; o painel admin (protegido por senha na página) grava.
--    (Pode ser endurecido depois com autenticação.)
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read_produtos" ON produtos;
CREATE POLICY "anon_read_produtos" ON produtos FOR SELECT USING (true);
DROP POLICY IF EXISTS "anon_write_produtos" ON produtos;
CREATE POLICY "anon_write_produtos" ON produtos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_read_config" ON config;
CREATE POLICY "anon_read_config" ON config FOR SELECT USING (true);
DROP POLICY IF EXISTS "anon_write_config" ON config;
CREATE POLICY "anon_write_config" ON config FOR ALL USING (true) WITH CHECK (true);
